
name = 'Please enter your name.'
name_error = 'You should have a name.'
ask_class = 'Please Choose a class for yourself. But choose wisely , because later you can\'t change it.'
attributes = 'Each class has their own attributes.'
warrior_des = 'Warrior is not a genius , but strong enough that it does not have to be. He mostly rely on his physichal strength in battles.\n'
warrior = '-Strength: 7\n-Inteligence: 3\n-Luck: 5\n-Speed: 5'
mage_des = 'Mage is not much of a muscleman, but inteligent enough to do magical attacks. He mostly use magic in battles.\n'
mage = '-Strength: 3\n-Inteligence: 7\n-Luck: 5\n-Speed: 5'
thief_des = 'Thief has average strenfth , but much faster then average. Mostlye relu on his speed in battles.\n'
thief = '-Strength: 5\n-Inteligence: 3\n-Luck: 5\n-Speed: 7'
choose_class_wrong_key = 'Please only choose from the following keys: W,M,T'
if_thief = 'Welcome, I hope you are going to proove yourself a good Thief.'
if_warrior = 'Welcome, I hope you are going to proove yourself a good Warrior.'
if_mage = 'Welcome, I hope you are going to proove yourself a good Mage.'
welcome_msg = 'Arnoldo de la Rosa, the king of kings , the lord of dragons, aaand local PIMP welcomes you.\nDo you wish to read the instructions before play? If yes , press R + Enter.\nIf you wish to play straight foward just press P + Enter.\nIf you are really a greenhorn, you can choose to display the function keys always, for that you have to press D + Enter.\nIf you are a coward and wish to run away anytime, just press X + Enter and the game will quit.'
